/**
 * Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * <p/>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p/>
 * Find the sum of all the even-valued terms in the sequence which do not exceed four million.
 */
public class Problem2 {

    public static void main(String[] args) {
        long fib1 = 1;
        long fib2 = 2;
        long fib3 = 0;
        long sum = 2; //first even! ya tambal! 

        int max = 4000000;

        System.out.println("1\n2");

        while (fib3 < max){
            fib3 = fib1 + fib2;

            if(fib3 % 2 != 0)
                System.out.println("odd  -> " + fib3);
            else{

                if(fib3  > max)
                    break;

                sum += fib3;
                System.out.println("even  -> " + fib3 + " update sum=" + sum);
            }
            fib1 = fib2;
            fib2 = fib3;

        }

        System.out.println("Sum of even fibs = " + sum);
    }
}
